### ISSUE TITLE
Ajouter les liens vers les CGV dans le panier

### ISSUE THREAD

**Issue by ngdo-pro** [wizaplace/starterkit#197]
### Besoin:
Afficher un lien vers les CGV de chaque vendeur des produits présents dans le panier pour que l'utilisateur puisse accepter celles-ci.

### Méthode:

- [ ] Créer une nouvelle route de type `/company/companyId/cgv`
- [ ] Y afficher les CGV ou `Ce vendeur n'a pas renseigné de CGV particulières` si il n'y a pas de `terms`
- [ ] Afficher les liens vers ces pages dans le checkout au moment du paiement.

**Comment by sergemazille** [comment]
C'est toujours d'actualité ?

**Comment by ngdo-pro** [comment]
Je pense que oui :thinking:
