### ISSUE TITLE
Home > Slider nouveauté

### ISSUE THREAD

**Issue by DavidFyon** [wizaplace/starterkit#221]
le slider nouveautés est trop large et créé une marge à droite sur tout le site

<img width="1350" alt="capture d ecran 2018-01-05 a 16 12 20" src="https://user-images.githubusercontent.com/1822420/34614915-56632184-f233-11e7-92da-40f61c1f77c2.png">

**Comment by sergemazille** [comment]
fait dans https://github.com/wizaplace/starterkit/pull/287
