### ISSUE TITLE
Ajout au panier ne marche pas 

### ISSUE THREAD

**Issue by SalvaCrea** [wizaplace/starterkit#288]
Sur la page produit et home, l'ajout au panier ne marche pas.
Je pourrais résoudre ce problème après.

![image](https://user-images.githubusercontent.com/18017015/37771039-9cdb66ce-2dd6-11e8-99d2-49175d8edd19.png)

Je dirais que c'est pas forcément un problème du starterKit

**Comment by ngdo-pro** [comment]
non, là, c'est un problème de produit configuré dans le BO
