### ISSUE TITLE
Problème création d'une Compagnie.

### ISSUE THREAD

**Issue by SalvaCrea** [wizaplace/starterkit#318]
![image](https://user-images.githubusercontent.com/18017015/38294086-0bd08614-37ea-11e8-9a0a-dc3db2fb0bc8.png)

Quand on veux enregistrer une entreprise via le SDK, le pays est obligatoire, alors qu'il n'est pas forcément demandé dans le cahier des charges.

Solution provisoire : 

![image](https://user-images.githubusercontent.com/18017015/38294121-2589db82-37ea-11e8-9467-8b7db0470aea.png)

**Comment by hectorj** [comment]
Ce n'est pas un bug. Si le design ne comporte pas de champ pour le pays, il faut que le controller en set un par défaut (comme tu as fait en fait si je comprends bien).

**Comment by hectorj** [comment]
(je ferme, mais si tu penses que c'est vraiment un bug tu peux ré-ouvrir)

**Comment by SalvaCrea** [comment]
Nop, c'est bon pour moi. Pour ce genre de bug, je continue à remonter ou c'est pas forcément utile ?

**Comment by hectorj** [comment]
Ca ne coûte pas grand chose de créer un ticket dans le doute :+1:
